/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

/**
 *
 * @author user
 */
public class Regla1 extends javax.swing.JFrame {

    /**
     * Creates new form Regla1
     */
    public Regla1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.q1Result.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreTabla1 = new javax.swing.JTextField();
        nombreTabla2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atributosTabla2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        atributosTabla1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        s1Queries = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        s2Queries = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        q1Result = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Creating Collections with Embedded Documents for Document Databases Taking into Account the Queries - Rule 1");

        jLabel2.setText("Nombre Tabla 1:");

        jLabel3.setText("Nombre Tabla 2:");

        nombreTabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTabla2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Atributos Tabla 1:");

        jLabel5.setText("Atributos Tabla 2:");

        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Ingrese los atributos de ambas tablas separados por comas, por favor no incluya caracteres especiales");

        atributosTabla2.setColumns(20);
        atributosTabla2.setRows(5);
        jScrollPane1.setViewportView(atributosTabla2);

        atributosTabla1.setColumns(20);
        atributosTabla1.setRows(5);
        jScrollPane2.setViewportView(atributosTabla1);

        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Ingrese los atributos de cada query separados por coma. Presione enter después de ingresar los atributos de cada query ");

        jLabel8.setText("Atributos S1:");

        jLabel9.setText("Atributos S2:");

        s1Queries.setColumns(20);
        s1Queries.setRows(5);
        jScrollPane3.setViewportView(s1Queries);

        s2Queries.setColumns(20);
        s2Queries.setRows(5);
        jScrollPane4.setViewportView(s2Queries);

        jButton1.setText("Obtener Q'");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        q1Result.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q1Result.setForeground(new java.awt.Color(0, 153, 153));
        q1Result.setText("Q':");

        volver.setText("Volver al Menú Principal");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(nombreTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nombreTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(200, 200, 200))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(jLabel4)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(82, 82, 82))))
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(q1Result)))
                        .addContainerGap(114, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButton1)
                .addGap(91, 91, 91)
                .addComponent(volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(volver))
                .addGap(33, 33, 33)
                .addComponent(q1Result)
                .addGap(206, 206, 206))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTabla2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTabla2ActionPerformed

    //Obtiene el resultado de la union de dos conjuntos
    private ArrayList<String> union(ArrayList<String> conjunto1, ArrayList<String> conjunto2) {
        ArrayList<String> Q = new ArrayList<>();
        Q.addAll(conjunto1);

        for (String conjunto2i : conjunto2) {
            if (!Q.contains(conjunto2i)) {
                Q.add(conjunto2i);
                //System.out.println(conjunto2i);
            }
        }
        //System.out.println(Q.size());
        return Q;
    }

    //Obtiene el conjunto interseccion de dos conjuntos
    private ArrayList<String> interseccion(String[] conjunto1, ArrayList<String> conjunto2) {
        ArrayList<String> conjuntoI = new ArrayList<>();

        for (int j = 0; j < conjunto1.length; j++) {
            if (conjunto2.contains(conjunto1[j])) {
                conjuntoI.add(conjunto1[j]);
            }
        }
        //System.out.println(conjuntoI.size());
        return conjuntoI;
    }

    //Determinar si dos conjuntos son iguales (Mismos elementos, en el mismo orden)
    private boolean elementosIguales(String[] conjunto1, ArrayList<String> conjunto2) {
        ArrayList<String> castConjunto1 = new ArrayList<>();
        castConjunto1.addAll(Arrays.asList(conjunto1));

        Collections.sort(castConjunto1);
        Collections.sort(conjunto2);

        return castConjunto1.equals(conjunto2);
    }

    //Devuelve el conjunto resultado de la diferencia entre  dos conjuntos
    private ArrayList<String> diferenciaConjuntos(String[] conjuntoS1, ArrayList<String> conjuntoT2S2) {
        ArrayList<String> conjuntoS1_T2S2 = new ArrayList<>();
        ArrayList<String> atributosS1i = new ArrayList<>();

        for (String conjuntoS1i : conjuntoS1) {
            String[] s1Atributos = conjuntoS1i.split("\\s*,\\s*");
            for (String S1i : s1Atributos) {
                if (!conjuntoT2S2.contains(S1i)) {
                    atributosS1i.add(S1i);
                }
            }

            if (!atributosS1i.isEmpty() && !elementosIguales(s1Atributos, atributosS1i)) {
                conjuntoS1_T2S2.addAll(atributosS1i);
            }
        }

        //Guardar solo los atributos unicos obtenidos de la diferencia
        ArrayList<String> unicosConjuntoS1_T2S2 = new ArrayList<>();
        
        for(String sti: conjuntoS1_T2S2){
            if (!unicosConjuntoS1_T2S2.contains(sti)){
                unicosConjuntoS1_T2S2.add(sti);
            }
        }

        return unicosConjuntoS1_T2S2;
    }

    private ArrayList<String> obtenerTDoblePrima(String[] conjuntoS1, ArrayList<String> conjuntoT2S2) {
        ArrayList<String> tDoblePrima = new ArrayList<>();

        for (String conjuntoS1i : conjuntoS1) {
            String[] s1Atributos = conjuntoS1i.split("\\s*,\\s*");
            if (this.interseccion(s1Atributos, conjuntoT2S2).isEmpty()) {
                tDoblePrima.addAll(Arrays.asList(s1Atributos));
            }
        }
        return tDoblePrima;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.q1Result.setText("");
        //String[] T1 = atributosTabla1.getText().split("\\s*,\\s*");
        String[] T2 = atributosTabla2.getText().split("\\s*,\\s*");

        String[] conjuntoS1 = s1Queries.getText().split("(\n|\r)");
        String[] conjuntoS2 = s2Queries.getText().split("(\n|\r)");

        ArrayList<String> conjuntoT2S2 = new ArrayList<>();
        ArrayList<String> conjuntoT2 = new ArrayList<>();
        conjuntoT2.addAll(Arrays.asList(T2));

        for (String conjuntoS2i : conjuntoS2) {
            String[] s2Atributos = conjuntoS2i.split("\\s*,\\s*");
            for (String S2i : s2Atributos) {
                if (conjuntoT2.contains(S2i) && !conjuntoT2S2.contains(S2i)) {
                    conjuntoT2S2.add(S2i);
                    //System.out.println(S2i);
                }
            }
        }

        ArrayList<String> s1SinT2S2 = this.diferenciaConjuntos(conjuntoS1, conjuntoT2S2);
        ArrayList<String> tPrima2 = this.union(conjuntoT2S2, s1SinT2S2);
        ArrayList<String> tDoblePrima = this.obtenerTDoblePrima(conjuntoS1, conjuntoT2S2);


        String qPrima = "Q'={" + atributosTabla1.getText() + ", "
                + this.nombreTabla2.getText() + "_of_"
                + this.nombreTabla1.getText() + ":{";

        for (int i = 0; i < tPrima2.size(); i++) {
            qPrima = qPrima + tPrima2.get(i) + ",";
        }

        qPrima = qPrima.substring(0, qPrima.length() - 1) + "}";
        
        if (tDoblePrima.isEmpty()){
            qPrima = qPrima + "}";
        }else{
            qPrima = qPrima + ", T''2:{";
            for (String tPi: tDoblePrima){
                qPrima = qPrima + tPi + ",";
            }
            qPrima = qPrima.substring(0, qPrima.length() - 1) + "}}";
        }


        this.q1Result.setVisible(true);
        this.q1Result.setText(qPrima);

        //this.interseccion(T1, T2);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regla1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atributosTabla1;
    private javax.swing.JTextArea atributosTabla2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nombreTabla1;
    private javax.swing.JTextField nombreTabla2;
    private javax.swing.JLabel q1Result;
    private javax.swing.JTextArea s1Queries;
    private javax.swing.JTextArea s2Queries;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
